### ISSUE TITLE
Avoid the long folder name

### ISSUE THREAD

**Issue by heticor915** [LiveOverflow/liveoverflow_youtube#1]
Hi, 
I'd like to suggest you that please try to use short names for the folders, sometimes by the resolution of my laptop ( 10.1" ) and  a single monitor configuration in my desktop looks difficult to me, it's just a wish for me and maybe others, you could use standard rules for the folders ej **youtubechapter_subfolder.**

![Desktop](http://i.imgur.com/zL6YI2k.png)
![Laptop](http://i.imgur.com/vnE4xlZ.png)
Take the folder  **0x05_simple_crackme_intro_assembler** as an example, after standarize that it would look like this :

``` shell
heticor915RE@devilmachine ~/LiveOverflow/0x05$
heticor915RE@devilmachine ~/LiveOverflow/0x06_1$
heticor915RE@devilmachine ~/LiveOverflow/0x07$
heticor915RE@devilmachine ~/LiveOverflow/0x07_09$
```

Regards, 
Hector.
Keep up the good work.

**Comment by UserXGnu** [comment]
On that matter, you could use zsh themed with something like oh-my-zsh instead of bash or just theme your own bash $PS1 environment variable so that I could fit the large folder name on the vte window. Just suggestions ^^

**Comment by heticor915** [comment]
Hi, 
In my case I just prefer to use bash,  in the past I was using fish but to avoid the compatibility with the possix standard, check [1](http://unix.stackexchange.com/questions/145522/what-does-it-mean-to-be-sh-compatible), my porpouse is a good option, at least I guess.

What would your bash settings for my case :sunglasses:, if you would like to share. :smile:.

**Comment by UserXGnu** [comment]
Sorry for the delay, I don't use bash for quite a long time, zsh rules, in case you change your mind and decide to use zsh, just tell me, I could share my configuration file, or you could simply use Oh-My-zsh....
