### ISSUE TITLE
compiling program

### ISSUE THREAD

**Issue by mahidsec** [LiveOverflow/liveoverflow_youtube#14]
sorry for asking this kind of question. can you please tell me how did you compile this program? I tried to compile the same program but in disassembly this shows some extra line, not doing something extra but some extra lines.

**Comment by AbdulConsole** [comment]
Run the command ‘gcc -v’ to check if you have a compiler installed. If not you need to download a gcc compiler and install it. 

Then run the command 'gcc program.c' After this, an executable file will be created in the directory that your c file exists in. Eg: program.exe

Now run can run 'program' to execute the program. 

You can also use online compilers too like
replit.com , onlinegdb.com , jdoodle.com , godbolt.com

**Comment by mahidsec** [comment]
Hey thanks for the suggestion. It fixes on its own and somehow I forgot to close this issue sorry for the inconvenience 😓
