### ISSUE TITLE
license_1

### ISSUE THREAD

**Issue by DjarDjar** [LiveOverflow/liveoverflow_youtube#8]
Basically  I type "gdb license_1" in Terminal and it opens the program, pretty much everything is fine up to this point.  Then I follow the instructions until I have to type "run". So I type it and run it and then gets some wired error that says "cannot execute: Permission Denied, During startup program exited with code 126". So please can you help me?

**Comment by SamuPert** [comment]
Maybe your program hasn't executable flag set.
Try run this command:
chmod +x license_1

**Comment by DjarDjar** [comment]
U know.... I had this problem 2 months ago lol.

**Comment by pitust** [comment]
Is it fixed?
